module.exports = {
  content: ['./template-parts/cover/cover-home.php', './src/**/*.js'],
  theme: {
    extend: {
      gridTemplateColumns: {
        14: 'repeat(14, minmax(0, 1fr))',
        16: 'repeat(16, minmax(0, 1fr))',
      },
    },
    spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        1.5: 'var(--space-1-5)',
        2: 'var(--space-2)',
        2.5: 'var(--space-2-5)',
        3: 'var(--space-3)',
        3.5: 'var(--space-3-5)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        28: 'var(--space-28)',
        32: 'var(--space-32)',
        36: 'var(--space-36)',
        40: 'var(--space-40)',
        44: 'var(--space-44)',
        48: 'var(--space-48)',
        52: 'var(--space-52)',
        56: 'var(--space-56)',
        60: 'var(--space-60)',
        64: 'var(--space-64)',
        72: 'var(--space-72)',
        80: 'var(--space-80)',
        96: 'var(--space-96)',


      '96-to-48': 'var(--space-96-to-48)',
      '48-to-32': 'var(--space-48-to-32)',


      '0-to-36': 'var(--space-0-to-36)',
      '0-to-48': 'var(--space-0-to-48)',
    },
    screens: {
      // => @media (min-width: 640px) { ... }
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      xxl: '1920px',
    },
    fontSize: {
      '14': 'var(--step-14)',
      '16': 'var(--step-16)',
      '18': 'var(--step-18)',
      '22': 'var(--step-22)',
      '28': 'var(--step-28)',
      '34': 'var(--step-34)',
      '38': 'var(--step-38)',
      '42': 'var(--step-42)',
    },
    colors: {
        primary: 'var(--primary)',
        primarydark: 'var(--primarydark)',
        light: 'var(--light)',
        dark: 'var(--dark)',
        white: 'var(--white)',
        gray: 'var(--gray)',
    },
  },
  corePlugins: {
    container: false, // if false, removes max-width fixed to breakpoints
  },
  plugins: [
    ({ addComponents, theme }) => {
      addComponents({
        '.container': {
          maxWidth: 'var(--container-max-width)',
          margin: '0 auto',
        },
        '.container-fluid': {
          maxWidth: 'var(--container-fluid-width)',
        },
        '.container-indent': {
          maxWidth: 'var(--container-indent-width)',
          margin: '0 auto',
        },
        '.button--primary': {
          border: "2px solid var(--primary)",
          background: "var(--primary)",
          color: "var(--white)",
          display: "inline-block",
          transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
          "padding-top": "var(--space-2)",
          "padding-bottom": "var(--space-2)",
          "padding-left": "var(--space-5)",
          "padding-right": "var(--space-5)",
          "border-radius": "9999px",
          'line-height': '1.6',
          'font-weight': '600',
          'font-size': 'var(--step-18)',
          cursor: "pointer",
          '&:hover': {
            'border-color': 'var(--primarydark)',
            background: "var(--primarydark)",
            color: "var(--white)",
          },
        },
        '.button--outline': {
          border: "2px solid var(--primary)",
          background: "var(--white)",
          color: "var(--primary)",
          display: "inline-block",
          transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
          "padding-top": "var(--space-2)",
          "padding-bottom": "var(--space-2)",
          "padding-left": "var(--space-5)",
          "padding-right": "var(--space-5)",
          "border-radius": "9999px",
          'line-height': '1.6',
          'font-weight': '600',
          'font-size': 'var(--step-18)',
          cursor: "pointer",
          '&:hover': {
            'border-color': 'var(--primarydark)',
            color: "var(--primarydark)",
          },
        },
      });
    },
  ],
};
